#!/usr/bin/env bash
# displays Best School 10 times.

Cmpt=1
while [ $Cmpt -lt 11 ]
do
    if [ $Cmpt = 4 ]
    then
        echo "bad luck"
    elif [ $Cmpt = 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((Cmpt++))
done
