#!/bin/bash
sudo apt-get update
sudo apt-get install ufw -y
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
echo "
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
COMMIT
" | sudo tee -a /etc/ufw/before.rules
sudo ufw disable
sudo ufw enable
sudo ufw status
